name: WalletAndroid-SDK-Tests

on:
  pull_request:
    branches:
      - main
      - release/**

env:
  PACKAGE_TYPE: "aar"
  GRADLE_VERSION: "8.8.2"
  JAVA_VERSION: "17"
  ARTIFACT_PATH: "VCL/build/outputs"
  MAVEN_CENTRAL_TOKEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
  MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
  MAVEN_CENTRAL_SIGNING_KEY_ID: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
  MAVEN_CENTRAL_SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_SIGNING_PASSWORD }}
  MAVEN_CENTRAL_PRIVATE_KEY_GPG_B64: ${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_GPG_B64 }}

jobs:
  test-android-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Import GPG Key (dry-run)
        if: github.event.pull_request.head.repo.full_name == github.repository
        shell: bash {0}
        run: |
          echo "${{ secrets.MAVEN_CENTRAL_PRIVATE_KEY_GPG_B64 }}" | base64 --decode > test_key.asc
          if ! gpg --dry-run --import test_key.asc; then
            echo "❌ Invalid or missing GPG key"
            exit 1
          fi

      - name: Check if sources JAR exists after build
        run: |
          ./gradlew assembleRelease sourcesJar
          test -f VCL/build/libs/vcl-sources.jar || (echo "❌ vcl-sources.jar not generated" && exit 1)
