name: WalletAndroid-SDK-Tests

on:
  pull_request:
    branches:
      - main
      - release/**

env:
  PACKAGE_TYPE: "aar"
  GRADLE_VERSION: "8.4"
  JAVA_VERSION: "17"
  ARTIFACT_PATH: "VCL/build/outputs"
jobs:
  test-android-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4
      # Setup java
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{ env.JAVA_VERSION }}
      # Run test
      - name: Run Test
        run: ./gradlew test